active_manager/urls.py
from django.contrib import admin
from django.urls import include,path
from gainspend import views as core_views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', core_views.signup, name='signup'),
    path('', include('gainspend.urls')),
    path('admin/', admin.site.urls),
]

gainspend/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ------------------------------ MOVEMENT -----------------------------------
    path('',views.main_dashboard, name='main_dashboard'),
    path('register_method_completion/',views.register_method_completion, name='register_method_completion'),
    path('successful_excercise/',views.successful_excercise, name='successful_excercise'),
    path('preface_interpolacion_lineal/',views.preface_interpolacion_lineal, name='preface_interpolacion_lineal'),
    path('preface_interpolacion_lineal/excercise',views.excercise_interpolacion_lineal, name='excercise_interpolacion_lineal'),
    path('preface_newton_hacia_adelante/',views.preface_newton_hacia_adelante, name='preface_newton_hacia_adelante'),
    path('preface_newton_hacia_adelante/excercise',views.excercise_newton_hacia_adelante, name='excercise_newton_hacia_adelante'),
    path('preface_newton_hacia_atras/',views.preface_newton_hacia_atras, name='preface_newton_hacia_atras'),
    path('preface_newton_hacia_atras/excercise',views.excercise_newton_hacia_atras, name='excercise_newton_hacia_atras'),
    path('preface_newton_con_diferencias_divididas/',views.preface_newton_con_diferencias_divididas, name='preface_newton_con_diferencias_divididas'),
    path('preface_newton_con_diferencias_divididas/excercise',views.excercise_newton_con_diferencias_divididas, name='excercise_newton_con_diferencias_divididas'),
    path('preface_lagrange/',views.preface_lagrange, name='preface_lagrange'),
    path('preface_lagrange/excercise',views.excercise_lagrange, name='excercise_lagrange'),
    path('preface_punto_fijo/',views.preface_punto_fijo, name='preface_punto_fijo'),
    path('preface_punto_fijo/excercise',views.excercise_punto_fijo, name='excercise_punto_fijo'),
    path('preface_grafico/',views.preface_grafico, name='preface_grafico'),
    path('preface_grafico/excercise',views.excercise_grafico, name='excercise_grafico'),
    path('preface_bisectriz/',views.preface_bisectriz, name='preface_bisectriz'),
    path('preface_bisectriz/excercise',views.excercise_bisectriz, name='excercise_bisectriz'),
    path('preface_newton_raphson/',views.preface_newton_raphson, name='preface_newton_raphson'),
    path('preface_newton_raphson/excercise',views.excercise_newton_raphson, name='excercise_newton_raphson'),
    path('preface_falsa_posicion/',views.preface_falsa_posicion, name='preface_falsa_posicion'),
    path('preface_falsa_posicion/excercise',views.excercise_falsa_posicion, name='excercise_falsa_posicion'),
    path('preface_secante/',views.preface_secante, name='preface_secante'),
    path('preface_secante/excercise',views.excercise_secante, name='excercise_secante'),
    path('preface_montante/',views.preface_montante, name='preface_montante'),
    path('preface_montante/excercise',views.excercise_montante, name='excercise_montante'),
    path('preface_gauss_jordan/',views.preface_gauss_jordan, name='preface_gauss_jordan'),
    path('preface_gauss_jordan/excercise',views.excercise_gauss_jordan, name='excercise_gauss_jordan'),
    path('preface_eliminacion_gaussiana/',views.preface_eliminacion_gaussiana, name='preface_eliminacion_gaussiana'),
    path('preface_eliminacion_gaussiana/excercise',views.excercise_eliminacion_gaussiana, name='excercise_eliminacion_gaussiana'),
    path('preface_gauss_seidel/',views.preface_gauss_seidel, name='preface_gauss_seidel'),
    path('preface_gauss_seidel/excercise',views.excercise_gauss_seidel, name='excercise_gauss_seidel'),
    path('preface_jacobi/',views.preface_jacobi, name='preface_jacobi'),
    path('preface_jacobi/excercise',views.excercise_jacobi, name='excercise_jacobi'),
    path('preface_linea_recta/',views.preface_linea_recta, name='preface_linea_recta'),
    path('preface_linea_recta/excercise',views.excercise_linea_recta, name='excercise_linea_recta'),
    path('preface_cuadratica/',views.preface_cuadratica, name='preface_cuadratica'),
    path('preface_cuadratica/excercise',views.excercise_cuadratica, name='excercise_cuadratica'),
    path('preface_cubica/',views.preface_cubica, name='preface_cubica'),
    path('preface_cubica/excercise',views.excercise_cubica, name='excercise_cubica'),
    path('preface_lineal_con_funcion/',views.preface_lineal_con_funcion, name='preface_lineal_con_funcion'),
    path('preface_lineal_con_funcion/excercise',views.excercise_lineal_con_funcion, name='excercise_lineal_con_funcion'),
    path('preface_cuadratica_con_funcion/',views.preface_cuadratica_con_funcion, name='preface_cuadratica_con_funcion'),
    path('preface_cuadratica_con_funcion/excercise',views.excercise_cuadratica_con_funcion, name='excercise_cuadratica_con_funcion'),
    path('preface_regla_trapezoidal/',views.preface_regla_trapezoidal, name='preface_regla_trapezoidal'),
    path('preface_regla_trapezoidal/excercise',views.excercise_regla_trapezoidal, name='excercise_regla_trapezoidal'),
    path('preface_newton_cotes_cerradas/',views.preface_newton_cotes_cerradas, name='preface_newton_cotes_cerradas'),
    path('preface_newton_cotes_cerradas/excercise',views.excercise_newton_cotes_cerradas, name='excercise_newton_cotes_cerradas'),
    path('preface_newton_cotes_abiertas/',views.preface_newton_cotes_abiertas, name='preface_newton_cotes_abiertas'),
    path('preface_newton_cotes_abiertas/excercise',views.excercise_newton_cotes_abiertas, name='excercise_newton_cotes_abiertas'),
    path('preface_regla_un_tercio_de_simpson/',views.preface_regla_un_tercio_de_simpson, name='preface_regla_un_tercio_de_simpson'),
    path('preface_regla_un_tercio_de_simpson/excercise',views.excercise_regla_un_tercio_de_simpson, name='excercise_regla_un_tercio_de_simpson'),
    path('preface_regla_tres_octavos_de_simpson/',views.preface_regla_tres_octavos_de_simpson, name='preface_regla_tres_octavos_de_simpson'),
    path('preface_regla_tres_octavos_de_simpson/excercise',views.excercise_regla_tres_octavos_de_simpson, name='excercise_regla_tres_octavos_de_simpson'),
    path('preface_euler_hacia_adelante/',views.preface_euler_hacia_adelante, name='preface_euler_hacia_adelante'),
    path('preface_euler_hacia_adelante/excercise',views.excercise_euler_hacia_adelante, name='excercise_euler_hacia_adelante'),
    path('preface_euler_hacia_atras/',views.preface_euler_hacia_atras, name='preface_euler_hacia_atras'),
    path('preface_euler_hacia_atras/excercise',views.excercise_euler_hacia_atras, name='excercise_euler_hacia_atras'),
    path('preface_euler_modificado/',views.preface_euler_modificado, name='preface_euler_modificado'),
    path('preface_euler_modificado/excercise',views.excercise_euler_modificado, name='excercise_euler_modificado'),
    path('preface_runge_kutta_segundo_orden/',views.preface_runge_kutta_segundo_orden, name='preface_runge_kutta_segundo_orden'),
    path('preface_runge_kutta_segundo_orden/excercise',views.excercise_runge_kutta_segundo_orden, name='excercise_runge_kutta_segundo_orden'),
    path('preface_runge_kutta_tercer_orden/',views.preface_runge_kutta_tercer_orden, name='preface_runge_kutta_tercer_orden'),
    path('preface_runge_kutta_tercer_orden/excercise',views.excercise_runge_kutta_tercer_orden, name='excercise_runge_kutta_tercer_orden'),
    path('preface_runge_kutta_cuarto_orden_por_un_tercio_de_simpson/',views.preface_runge_kutta_cuarto_orden_por_un_tercio_de_simpson, name='preface_runge_kutta_cuarto_orden_por_un_tercio_de_simpson'),
    path('preface_runge_kutta_cuarto_orden_por_un_tercio_de_simpson/excercise',views.excercise_runge_kutta_cuarto_orden_por_un_tercio_de_simpson, name='excercise_runge_kutta_cuarto_orden_por_un_tercio_de_simpson'),
    path('preface_runge_kutta_cuarto_orden_por_tres_octavos_de_simpson/',views.preface_runge_kutta_cuarto_orden_por_tres_octavos_de_simpson, name='preface_runge_kutta_cuarto_orden_por_tres_octavos_de_simpson'),
    path('preface_runge_kutta_cuarto_orden_por_tres_octavos_de_simpson/excercise',views.excercise_runge_kutta_cuarto_orden_por_tres_octavos_de_simpson, name='excercise_runge_kutta_cuarto_orden_por_tres_octavos_de_simpson'),
    path('preface_runge_kutta_de_orden_superior/',views.preface_runge_kutta_de_orden_superior, name='preface_runge_kutta_de_orden_superior'),
    path('preface_runge_kutta_de_orden_superior/excercise',views.excercise_runge_kutta_de_orden_superior, name='excercise_runge_kutta_de_orden_superior'),
]

gainspend/models.py
from django.db import models
from django.contrib.auth.models import User

class Method(models.Model):
    field_id = models.IntegerField(db_column='_id', primary_key=True, blank=True)
    name = models.TextField(blank=True, null=True)
    is_subject = models.BooleanField(blank=True, null=True)
    preface_name = models.TextField(blank=True, null=True)

class UserMethod(models.Model):
    field_id = models.IntegerField(db_column='_id', primary_key=True, blank=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete = models.CASCADE)
    method = models.ForeignKey(Method, null=True, blank=True, on_delete = models.CASCADE)
    seconds = models.IntegerField(blank=True, null=True)

gainspend/forms.py
from django import forms
from .models import UserMethod

class UserMethodForm(forms.ModelForm):
    method_id = forms.IntegerField()
    class Meta:
        model = UserMethod
        fields = ('method_id','seconds')

gainspend/views/base_views.py
from django.shortcuts import render
from gainspend.models import Method
from gainspend.models import UserMethod
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from gainspend.forms import UserMethodForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.core import serializers

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('main_dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

@login_required
def main_dashboard(request):
    # Dump data into json file - start
    # data = serializers.serialize("json", UserMethod.objects.all())
    # out = open("gainspend/fixtures/user_methods.json", "w")
    # out.write(data)
    # out.close()
    # Dump data into json file - end
    methods = Method.objects.all()
    completed_list = []
    seconds_list = []
    second_tag_colors = []
    for method in methods:
        user_methods = UserMethod.objects.filter(user=request.user, method=method)
        completed = len(user_methods)
        if completed >= 1:
            completed_list.append(True)
            seconds = user_methods.order_by('seconds').first().seconds
            seconds_list.append(seconds)
            if seconds <= 180:
                second_tag_colors.append("green")
            elif seconds <= 360:
                second_tag_colors.append("yellow darken-4")
            else:
                second_tag_colors.append("red")
        else:
            completed_list.append(False)
            seconds_list.append(0)
            second_tag_colors.append("")
    completed_list.insert(0,True)
    completed_list[1] = True
    methods_list = zip(methods, completed_list, seconds_list, second_tag_colors)
    context = {
        "methods_list": methods_list
    }
    return render(request, 'gainspend/pages/main_dashboard.html', context)

@login_required
def successful_excercise(request):
    context = {
    }
    return render(request, 'gainspend/pages/successful_excercise.html', context)


@login_required
def register_method_completion(request):
    if request.method == 'POST':
        form = UserMethodForm(request.POST)
        if form.is_valid():
            post_seconds = form.cleaned_data['seconds']
            print(form.cleaned_data['method_id'])
            post_method = Method.objects.get(field_id = form.cleaned_data['method_id'])
            print(post_method)
            user_method = UserMethod(
                user = request.user,
                method = post_method,
                seconds = post_seconds
            )
            user_method.save()
            # If next method is a subject, then mark it as completed to enable it in main_dashboard
            try:
                next_method = Method.objects.get(field_id = (post_method.field_id + 1))
            except Exception as e:
                print(e)
                return redirect("successful_excercise")
            if next_method.is_subject:
                next_user_method = UserMethod(
                    user = request.user,
                    method = next_method,
                    seconds = 0
                )
                next_user_method.save()
            return redirect("successful_excercise")
        else:
            return redirect("main_dashboard")
    else:
        return redirect("main_dashboard")

gainspend/templates/gainspend/utilities/excercise_bisectriz_start_excercise_box.html
<div id="start_excercise_box" class="hide">
  <div class="row">
    <div class="col s12 m9">
      <label >
      <input id="no_tiene_solucion" type="checkbox" class="filled-in" />
      <span style="color:black !important;font-size: 25px;">¿Existe raíz?</span>
    </label>
    </div>
    <div id="validar_respuesta" class="col s12 m3 btn btn-large green hoverable" style="margin-top:20px;">
      Validar respuesta
    </div>
  </div>
</div>

gainspend/templates/gainspend/utilities/excercise_cuadratica_answer_script.html
// Funcion de Validacion de respuesta
function sort_of_equal(v1, v2, epsilon) {
  if (epsilon == null) {
    epsilon = 0.001;
  }
  return Math.abs(v1 - v2) < epsilon;
};
function validar_respuesta() {
  if ($("#no_tiene_solucion").is(":checked")) {
    if (excercise_answer_a0 == "No hay solucion") {
      mandar_formulario();
      // console.log("Yei");
    } else {
      $("#valor_a0").addClass("invalid");
      $("#valor_a1").addClass("invalid");
      $("#valor_a2").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  } else {
    valor_a0 = Number($("#valor_a0").val());
    valor_a1 = Number($("#valor_a1").val());
    valor_a2 = Number($("#valor_a2").val());
    if (sort_of_equal(valor_a0, excercise_answer_a0, 0.00001) && sort_of_equal(valor_a1, excercise_answer_a1, 0.00001) && sort_of_equal(valor_a2, excercise_answer_a2, 0.00001)) {
      mandar_formulario();
      // console.log("Yaaaas");
    } else {
      $("#valor_a0").addClass("invalid");
      $("#valor_a1").addClass("invalid");
      $("#valor_a2").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  }
}

function mandar_formulario() {
  form_seconds = $("#excercise_timer").data('seconds');
  console.log(form_seconds);
  $('#id_seconds').val(form_seconds);
  $("#user_method_form").submit();
}
// Aparecer probelma e iniciar timer
function iniciar_problema(){
  $("#start_excercise_box").removeClass("hide");
  $("#excercise_cover").addClass("hide");
  $("#excercise_timer").timer({
  action: 'start',
  duration: 600,
  callback: function() {
    location.reload();
  }
});
}
$("#validar_respuesta").on("click", function() {
  validar_respuesta();
});
$("#comenzar_problema").on("click", function() {
  iniciar_problema();
});

gainspend/templates/gainspend/utilities/excercise_cuadratica_start_excercise_box.html
<div id="start_excercise_box" class="hide">
  <div class="row">
    <div class="col s12 m9">
      <table>
        <tbody>
          <td style="width:50px;">g(x) =</td>
          <td>
            <input id="valor_a0" class="number_answer" type="number" value=""><br>
          </td>
          <td>+</td>
          <td>
            <input id="valor_a1" class="number_answer" type="number" value=""><br>
          </td>
          <td style="font-size: 20px; font-weight: bold;">x</td>
          <td>+</td>
          <td>
            <input id="valor_a2" class="number_answer" type="number" value=""><br>
          </td>
          <td style="font-size: 20px; font-weight: bold;">x^2</td>
        </tbody>
      </table>
      <p>
        <label>
          <input id="no_tiene_solucion" type="checkbox" class="filled-in" />
          <span>No tiene solucion</span>
        </label>
      </p>
    </div>
    <div id="validar_respuesta" class="col s12 m3 btn btn-large green hoverable" style="margin-top:20px;">
      Validar respuesta
    </div>
  </div>
</div>

gainspend/templates/gainspend/utilities/excercise_cubica_answer_script.html
// Funcion de Validacion de respuesta
function sort_of_equal(v1, v2, epsilon) {
  if (epsilon == null) {
    epsilon = 0.001;
  }
  return Math.abs(v1 - v2) < epsilon;
};
function validar_respuesta() {
  if ($("#no_tiene_solucion").is(":checked")) {
    if (excercise_answer_a0 == "No hay solucion") {
      mandar_formulario();
      // console.log("Yei");
    } else {
      $("#valor_a0").addClass("invalid");
      $("#valor_a1").addClass("invalid");
      $("#valor_a2").addClass("invalid");
      $("#valor_a3").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  } else {
    valor_a0 = Number($("#valor_a0").val());
    valor_a1 = Number($("#valor_a1").val());
    valor_a2 = Number($("#valor_a2").val());
    valor_a3 = Number($("#valor_a3").val());
    if (sort_of_equal(valor_a0, excercise_answer_a0, 0.00001) && sort_of_equal(valor_a1, excercise_answer_a1, 0.00001) && sort_of_equal(valor_a2, excercise_answer_a2, 0.00001) && sort_of_equal(valor_a3, excercise_answer_a3, 0.00001)) {
      mandar_formulario();
      // console.log("Yaaaas");
    } else {
      $("#valor_a0").addClass("invalid");
      $("#valor_a1").addClass("invalid");
      $("#valor_a2").addClass("invalid");
      $("#valor_a3").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  }
}

function mandar_formulario() {
  form_seconds = $("#excercise_timer").data('seconds');
  console.log(form_seconds);
  $('#id_seconds').val(form_seconds);
  $("#user_method_form").submit();
}
// Aparecer probelma e iniciar timer
function iniciar_problema(){
  $("#start_excercise_box").removeClass("hide");
  $("#excercise_cover").addClass("hide");
  $("#excercise_timer").timer({
  action: 'start',
  duration: 600,
  callback: function() {
    location.reload();
  }
});
}
$("#validar_respuesta").on("click", function() {
  validar_respuesta();
});
$("#comenzar_problema").on("click", function() {
  iniciar_problema();
});

gainspend/templates/gainspend/utilities/excercise_cubica_start_excercise_box.html
<div id="start_excercise_box" class="hide">
  <div class="row">
    <div class="col s12 m9">
      <table>
        <tbody>
          <tr>
            <td style="width:50px;">g(x) =</td>
            <td>
              <input id="valor_a0" class="number_answer" type="number" value="">
            </td>
            <td>+</td>
            <td>
              <input id="valor_a1" class="number_answer" type="number" value="">
            </td>
            <td style="font-size: 20px; font-weight: bold;">x</td>
            <td></td>
          </tr>
        </tbody>
      </table>
      <table>
        <tbody>
          <tr>
            <td>+</td>
            <td>
               <input id="valor_a2" class="number_answer" type="number" value="">
            </td>
            <td style="font-size: 20px; font-weight: bold;">x^2</td>
            <td>+</td>
            <td>
               <input id="valor_a3" class="number_answer" type="number" value="">
            </td>
            <td style="font-size: 20px; font-weight: bold;">x^3</td>
          </tr>
        </tbody>
      </table>
      <p>
        <label>
          <input id="no_tiene_solucion" type="checkbox" class="filled-in" />
          <span>No tiene solucion</span>
        </label>
      </p>
    </div>
    <div id="validar_respuesta" class="col s12 m3 btn btn-large green hoverable" style="margin-top:20px;">
      Validar respuesta
    </div>
  </div>
</div>

gainspend/templates/gainspend/utilities/excercise_linea_recta_answer_script.html
// Funcion de Validacion de respuesta
function sort_of_equal(v1, v2, epsilon) {
  if (epsilon == null) {
    epsilon = 0.001;
  }
  return Math.abs(v1 - v2) < epsilon;
};
function validar_respuesta() {
  if ($("#no_tiene_solucion").is(":checked")) {
    if (excercise_answer_a0 == "No hay solucion") {
      mandar_formulario();
      // console.log("Yei");
    } else {
      $("#valor_a0").addClass("invalid");
      $("#valor_a1").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  } else {
    valor_a0 = Number($("#valor_a0").val());
    valor_a1 = Number($("#valor_a1").val());
    if (sort_of_equal(valor_a0, excercise_answer_a0, 0.00001) && sort_of_equal(valor_a1, excercise_answer_a1, 0.00001)) {
      mandar_formulario();
      // console.log("Yaaaas");
    } else {
      $("#valor_a0").addClass("invalid");
      $("#valor_a1").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  }
}

function mandar_formulario() {
  form_seconds = $("#excercise_timer").data('seconds');
  console.log(form_seconds);
  $('#id_seconds').val(form_seconds);
  $("#user_method_form").submit();
}
// Aparecer probelma e iniciar timer
function iniciar_problema(){
  $("#start_excercise_box").removeClass("hide");
  $("#excercise_cover").addClass("hide");
  $("#excercise_timer").timer({
  action: 'start',
  duration: 600,
  callback: function() {
    location.reload();
  }
});
}
$("#validar_respuesta").on("click", function() {
  validar_respuesta();
});
$("#comenzar_problema").on("click", function() {
  iniciar_problema();
});

gainspend/templates/gainspend/utilities/excercise_orden_superior_answer_script.html
// Funcion de Validacion de respuesta
function sort_of_equal(v1, v2, epsilon) {
  if (epsilon == null) {
    epsilon = 0.001;
  }
  return Math.abs(v1 - v2) < epsilon;
};
function validar_respuesta() {
  if ($("#no_tiene_solucion").is(":checked")) {
    if (excercise_answer_y1 == "No hay solucion") {
      mandar_formulario();
      // console.log("Yei");
    } else {
      $("#valor_y1").addClass("invalid");
      $("#valor_y1_prime").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  } else {
    valor_y1 = Number($("#valor_y1").val());
    valor_y1_prime = Number($("#valor_y1_prime").val());
    if (sort_of_equal(valor_y1, excercise_answer_y1, 0.00001) && sort_of_equal(valor_y1_prime, excercise_answer_y1_prime, 0.00001)) {
      mandar_formulario();
      // console.log("Yaaaas");
    } else {
      $("#valor_y1").addClass("invalid");
      $("#valor_y1_prime").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  }
}

function mandar_formulario() {
  form_seconds = $("#excercise_timer").data('seconds');
  console.log(form_seconds);
  $('#id_seconds').val(form_seconds);
  $("#user_method_form").submit();
}
// Aparecer probelma e iniciar timer
function iniciar_problema(){
  $("#start_excercise_box").removeClass("hide");
  $("#excercise_cover").addClass("hide");
  $("#excercise_timer").timer({
  action: 'start',
  duration: 600,
  callback: function() {
    location.reload();
  }
});
}
$("#validar_respuesta").on("click", function() {
  validar_respuesta();
});
$("#comenzar_problema").on("click", function() {
  iniciar_problema();
});

gainspend/templates/gainspend/utilities/excercise_single_answer_script.html
// Funcion de Validacion de respuesta
function sort_of_equal(v1, v2, epsilon) {
  if (epsilon == null) {
    epsilon = 0.001;
  }
  return Math.abs(v1 - v2) < epsilon;
};
function validar_respuesta() {
  if ($("#no_tiene_solucion").is(":checked")) {
    if (excercise_answer == "No hay solucion") {
      mandar_formulario();
    } else {
      $("#valor_x").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  } else {
    valor_x = Number($("#valor_x").val());
    if (sort_of_equal(valor_x, excercise_answer, .0000099999)) {
      mandar_formulario();
    } else {
      $("#valor_x").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  }
}

function mandar_formulario() {
  form_seconds = $("#excercise_timer").data('seconds');
  console.log(form_seconds);
  $('#id_seconds').val(form_seconds);
  $("#user_method_form").submit();
}
// Aparecer probelma e iniciar timer
function iniciar_problema(){
  $("#start_excercise_box").removeClass("hide");
  $("#excercise_cover").addClass("hide");
  $("#excercise_timer").timer({
    action: 'start',
    duration: 600,
    callback: function() {
      location.reload();
    }
  });
}
$("#validar_respuesta").on("click", function() {
  validar_respuesta();
});
$("#comenzar_problema").on("click", function() {
  iniciar_problema();
});

gainspend/templates/gainspend/utilities/excercise_single_answer_three_decimals_script.html
// Funcion de Validacion de respuesta
function sort_of_equal(v1, v2, epsilon) {
  if (epsilon == null) {
    epsilon = 0.001;
  }
  return Math.abs(v1 - v2) < epsilon;
};
function validar_respuesta() {
  if ($("#no_tiene_solucion").is(":checked")) {
    if (excercise_answer == "No hay solucion") {
      mandar_formulario();
    } else {
      $("#valor_x").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  } else {
    valor_x = Number($("#valor_x").val());
    if (sort_of_equal(valor_x, excercise_answer, .001)) {
      mandar_formulario();
    } else {
      $("#valor_x").addClass("invalid");
      swal(
        '¡Se ha equivocado!',
        'Revise su procedimiento y vuelva a intentar',
        'error'
      )
    }
  }
}

function mandar_formulario() {
  form_seconds = $("#excercise_timer").data('seconds');
  console.log(form_seconds);
  $('#id_seconds').val(form_seconds);
  $("#user_method_form").submit();
}
// Aparecer probelma e iniciar timer
function iniciar_problema(){
  $("#start_excercise_box").removeClass("hide");
  $("#excercise_cover").addClass("hide");
  $("#excercise_timer").timer({
  action: 'start',
  duration: 600,
  callback: function() {
    location.reload();
  }
});
}
$("#validar_respuesta").on("click", function() {
  validar_respuesta();
});
$("#comenzar_problema").on("click", function() {
  iniciar_problema();
});